### ISSUE TITLE
Don't automatically turn off screen on proximity in video mode

### ISSUE THREAD

**Issue by ndarilek** [zxcpoiu/react-native-incall-manager#1]
In video mode, I might very well want to touch the screen to interact during a call, particularly as it isn't near my ear. Therefore, I would suggest that the default behavior not turn off the screen on proximity in video mode. During audio mode is fine, or maybe better, when audio is through the earpiece and not the speaker. I could see using an audio call in speaker mode but being unable to because the default behavior kills the screen. I hit this behavior trying to activate a control I'd placed to toggle speaker mode. :)

Thanks!

**Comment by zxcpoiu** [comment]
yeah, I was considering the same issue, and you are right, disable proximity in video mode is better!

**Comment by zxcpoiu** [comment]
I am thinking of using a setting object in start() to decide the default behavior.

**Comment by zxcpoiu** [comment]
changed in 1.0.1.
video mode will not enable proximity sensor be default now.
