### ISSUE TITLE
There's no Objective-C Bridging Header in my build setting...Help!

### ISSUE THREAD

**Issue by dannyyaou** [zxcpoiu/react-native-incall-manager#12]
Dear Author of this module
thanks a lot for your contribution for rn
but...
There's no Objective-C Bridging Header in my build setting...
Please Help!!

**Comment by dannyyaou** [comment]
Fixed! I just don't follow last step! Sorry!
Please close this issue for me!

**Comment by zxcpoiu** [comment]
thanks for posting how you solves it :)
