### ISSUE TITLE
Android issues with runtime 

### ISSUE THREAD

**Issue by ganeshagrawal** [zxcpoiu/react-native-incall-manager#15]
I have setup the android project with following in build.gradle and all build fine. 

android {
....
    defaultConfig {
...
        targetSdkVersion 23
}

dependencies {
.....
compile 'com.android.support:support-v4:23.0.1'
.....
compile(project(':react-native-incall-manager')) {
        exclude group: 'com.facebook.react', module: 'react-native'
    }

.....
}

I get following auntie error:
Cannot read property 'checkRecordPermission' of undefined.

Looks like the project is not setup correctly and it is not able to resolve the incallmanager .

My build runs fine on iOS with no issues.

**Comment by ganeshagrawal** [comment]
Got it resolved.

**Comment by zxcpoiu** [comment]
Great
Would you mind sharing what's going on and how to solve it that I can put them into docs?
