### ISSUE TITLE
Problems setting up on IOS.

### ISSUE THREAD

**Issue by IvRRimum** [zxcpoiu/react-native-incall-manager#19]
So i added the `RNInCallManager` to my xcodeproject. And moved forward to next step:
`click your project's xcodeproject root, go to build setting and search Objective-C Bridging Header`
But when i search `Objective-C Bridging Header` in my project `build settings` nothing shows up?

Has something changed?

**Comment by IvRRimum** [comment]
Resolved the issue, but No audio is not played not sent(from my mic) in my react-native application on IOS devices. Any ideas?

**Comment by IvRRimum** [comment]
Some logs:
2016-12-22 22:53:49.532 YouRa[724:348200] RNInCallManager._checkRecordPermission(): using iOS8+ api. recordPermission=undetermined
2016-12-22 22:53:49.543 YouRa[724:348194] RNInCallManager._checkCameraPermission(): using iOS7 api. cameraPermission=undetermined

**Comment by zxcpoiu** [comment]
you should grant permissions accordingly.
the permission result should be 'grant'

**Comment by IvRRimum** [comment]
It was problem in other dependency. Resolved.

**Comment by zxcpoiu** [comment]
thanks for feedbacks @IvRRimum
