### ISSUE TITLE
state of speakers doesn't get restored after a phone call.

### ISSUE THREAD

**Issue by szymonzmyslony** [zxcpoiu/react-native-incall-manager#20]
I am using 1.5.1 version of this module and when I answer an incoming call, speakers are always forced off. Is that fixed in any new version. If not, how can I deal with it?

**Comment by zxcpoiu** [comment]
The default action of audio is speaker off by default
InCallManager.start({media: 'audio'});

If you're using video, use:

InCallManager.start({media: 'video'});

which is speaker on by default

**Comment by zxcpoiu** [comment]
please test it on the latest master
