### ISSUE TITLE
undefined is not an object _InCallManager.start

### ISSUE THREAD

**Issue by EdmundMai** [zxcpoiu/react-native-incall-manager#21]
I'm trying to install this for android and it's not working. All I did was

1) npm install
2) import InCallManager from 'react-native-incall-manager';
3) InCallManager.start()

And I am getting the error: `undefined is not an object (evaluating '_InCallManager.start')`

**Comment by igala** [comment]
same here, I get something similar, looks something is broken:

'InCallManager.requestRecordPermission() catch: ', { [TypeError: undefined is not an object (evaluating '_InCallManager.requestRecordPermission')]

**Comment by igala** [comment]
@EdmundMai  , I got it work, it seems I forgot to add the bridge header to the build settings.
Make sure the m and swift files are part of the compile phase.

**Comment by zxcpoiu** [comment]
Thanks @igala 

@EdmundMai 
Apart from @igala 's suggestions, It may also related to RN40 support
You may want to try latest master if you are using RN40+

**Comment by HongSeokHwan** [comment]
(Thank you for your great code)

I have same problem in android.

"react-native": "0.39.2"
"react-native-incall-manager": "1.5.4",


InCallManager.requestRecordPermission() catch:  TypeError: Cannot read property 'requestRecordPermission' of undefined

I think _InCallManager(in index.js) is undefined, but I don't know why.

**Comment by JamesToohey** [comment]
For anyone that has an issue with Android, I had to manually add the following to MainApplication.java

```
import com.zxcpoiu.incallmanager.InCallManagerPackage;
```

```
    @Override
    protected List<ReactPackage> getPackages() {
      mReactNativePushNotificationPackage = new ReactNativePushNotificationPackage();
      return Arrays.<ReactPackage>asList(
          new InCallManagerPackage(),
      );
    }
```

**Comment by fabriziomoscon** [comment]
@zxcpoiu 
I can confirm that `rnpm link react-native-incall-manager` did a partial job.
It added `import com.zxcpoiu.incallmanager.InCallManagerPackage;` into `MainActivity.java` rather than `MainApplication.java` and it didn't add `new InCallManagerPackage()` in the `getPackages()` method.

**Comment by zxcpoiu** [comment]
thanks @JamesToohey @fabriziomoscon

I'm not sure why though.
does this occurs on 2.1.0? ( react-native dependency >= 40 )

**Comment by idanhaviv** [comment]
hi @zxcpoiu @igala, 
 
i'm still getting this warning:
undefined is not an object (evaluating '_InCallManager.checkRecordPermission')

i'm on iOS, using react-native 0.42.0-rc.3, tried adding the RNInCallManager to the compile phase (xcode only lets me add the folder not the individual files), added the RNInCallManager' bridging header's contents to my app's bridging header, and tried RNInCallManager latest commit on master.

**Comment by joshuaalpuerto** [comment]
Hi @zxcpoiu,

First of all thanks for this awesome library!

I was able to get this library work on android but I'm having issue with IOS (10.3), using react-native 0.42.0.

```
Cannot read property 'checkCameraPermission' of undefined
TypeError: Cannot read property 'checkCameraPermission' of undefined

Cannot read property 'checkRecordPermission' of undefined
TypeError: Cannot read property 'checkRecordPermission' of undefined
```

Thanks!

**Comment by zxcpoiu** [comment]
@joshuaalpuerto 

It seems like an setup issue. means the entire incall-manager is undefined. ( not loaded )

Since I'm not test on 0.43 yet, so not sure if it is caused by react-native version or not. ( probably not )

anyway, I suggest you wipe this project entirely from your xcode and reinstall/configure it step by step carefully, be sure to double check your swift version, bridging header, library path and so on.

**Comment by joshuaalpuerto** [comment]
@zxcpoiu  Thanks for your reply!

Here's a screenshot of xcode hope you can help me.. 

Thanks a lot!

<img width="1312" alt="screen shot 2017-04-25 at 11 18 03 am" src="https://cloud.githubusercontent.com/assets/7126484/25367567/01a10e70-29a9-11e7-8b57-0a81f8616a36.png">

**Comment by joshuaalpuerto** [comment]
Silly me! I accidentally remove the `RNInCallManager` inside my node modules. I remove the library and reinstall now its working perfectly fine!

Thanks @zxcpoiu

**Comment by zxcpoiu** [comment]
nice, thanks for your feedback!

**Comment by zxcpoiu** [comment]
I have added android manually link in README, thanks!

**Comment by sagivo** [comment]
i checked the last version on master and I get the same error. even after trying to install manually again

**Comment by zxcpoiu** [comment]
@sagivo 

Android?

**Comment by sagivo** [comment]
@zxcpoiu IOS

**Comment by sagivo** [comment]
also i cannot test on the latest version that not in master as after installing i can't find the `.xcodeproj` file. i only see it when pointing to the latest version on master.

**Comment by zxcpoiu** [comment]
It seems like it was not installed properly to me.
Would you try `Clean project if messed up` to do the clean process described in `README`?

If you comment out `checkCameraPermission` and `checkRecordPermission`, I believe other functions are all undefined as well.

Make sure you remove `swift bridging header` that you added in the previous version and point your `react-native-incall-manager` install path to the github's latest master in the `package.json`

**Comment by zxcpoiu** [comment]
@sagivo 

You might want to try https://github.com/zxcpoiu/react-native-incall-manager/issues/59#issuecomment-351849745 that @jay0lu described
