### ISSUE TITLE
setSpeakerphoneOn(true) should disable turning off screen (by proximity)

### ISSUE THREAD

**Issue by ZahiC** [zxcpoiu/react-native-incall-manager#28]
Tested in android. 

Turning off the screen while the speaker is on is not the common behavior during phone calls. I guess it also true when the audio is routed to an external device

**Comment by zxcpoiu** [comment]
yes, I agreed.

should have a setup to let user to decide what behavior should be used.

**Comment by zxcpoiu** [comment]
Hi,

Android has refactored on the latest master.
The new behavior is like what you described.

Proximity sensor now only turn screen off when audio is routing to Ear Piece, otherwise, it will just send event and do nothing.
