### ISSUE TITLE
Get Swift Compiler Error when installing incall-manager on ios

### ISSUE THREAD

**Issue by shengzihong** [zxcpoiu/react-native-incall-manager#32]
I followed every single step on installation.

1, npm install react-native-incall-manager
2, react-native link react-native-incall-manager for android
3, In xcode, right click on your_project directory, add files to your project and add node_modules/react-native-incall-manager/ios/RNInCallManager/
4, Edit -> Convert -> To Current Swift Syntax To swift 3
5, Objective-C Bridging Header to ../node_modules/react-native-incall-manager/ios/RNInCallManager/RNInCallManager-Bridging-Header.h

And I finally ended up with these errors. This might caused by xcode not found the OC bridging header.
![image](https://cloud.githubusercontent.com/assets/7087667/25377874/4ed3bc10-29db-11e7-967f-bc1267b03481.png)

I was wondering is there anyone has the problem?

**Comment by MetinSeylan** [comment]
+1

**Comment by enricotelesca** [comment]
+1

**Comment by zxcpoiu** [comment]
thanks @enricotelesca 

is this mainly xcode swift upgrade issue or the regular setup issue?
if you find that current document lacks some important steps, feel free to send a PR to correct it :+1:

**Comment by MiracleDeveloper** [comment]
+1
But I have no luck to resolve by doing the same steps suggested by  @enricotelesca 
It seems just header issues, but I am not not familiar with xcode.
Any other suggestions?

Thanks

**Comment by HolaMan** [comment]
+1
But I have no luck to resolve by doing the same steps suggested by @enricotelesca
It seems just header issues, but I am not not familiar with xcode.
Any other suggestions?

Thanks

**Comment by cristiantx** [comment]
I can confirm that I was trying to run a fresh installation of InCall Manager in a RN 0.44 app and had to do what @enricotelesca stated. Thanks

**Comment by zxcpoiu** [comment]
As of #56, the iOS part has been changed it to objc and there is no swift anymore.
Please check latest master.
