### ISSUE TITLE
App crashing when connecting to/disconnecting from bluetooth headset during call

### ISSUE THREAD

**Issue by seb0zz** [zxcpoiu/react-native-incall-manager#34]
We use this module in combination with react-native-webrtc. Everything seems to be fine except connecting to or disconnecting from a bluetooth headset during an active call. All I get is the following exception in XCode:

```
#
# Fatal error in ../../../webrtc/modules/audio_device/audio_device_buffer.cc, line 242
# last system error: 0
# Check failed: num_samples == rec_samples_per_10ms_ (160 vs. 480)
# 
#
(lldb) 
```

This might also be related to [this issue](https://github.com/oney/react-native-webrtc/issues/84) from react-native-webrtc.

**Comment by zxcpoiu** [comment]
`react-native-incall-manager` doesn't implement/handle routing audio to bluetooth yet.
will find time to implement it.

currently, no clues in my head. but it did really surprised me that webrtc crashed by just connecting to bluetooth !? :scream: 

the issue you mentioned is discussed before this library. now all audio routing logics moved to here.

**Comment by zxcpoiu** [comment]
I'm not familiar with bluetooth framework 
but I was testing bluetooth before, the audio just not routing correctly, but never crash.


few questions:

1. are you using both latest version right? ( master in DEMO / 1.58.0 in react-native-webrtc )
2. does it occurs on both android and ios devices? or specific device/os?

**Comment by seb0zz** [comment]
Upgrading react-native-webrtc from 1.54.7 to 1.58.0 fixed it. Thank you 🎉

**Comment by seb0zz** [comment]
Btw. also the audio routing for the headphones works out of the box.

**Comment by konstantin-mohin** [comment]
@seb0zz 
is it working on Android devices ?
