### ISSUE TITLE
Freeze's timers on Samsung devices when proximity is near?

### ISSUE THREAD

**Issue by theaidem** [zxcpoiu/react-native-incall-manager#36]
The following code correctly works on a lot of devices:
```js
import React, { Component } from 'react'
import {
  AppRegistry,
  Text,
} from 'react-native'
import InCallManager from "react-native-incall-manager"

export default class Intervals extends Component {

  componentDidMount = () => {
    InCallManager.start({media: 'audio'})
    this.interval = setInterval(() => {
      console.log("tick!")
    }, 1000)
  }

  render() {
    return (
      <Text>Intervals</Text>
    )
  }
}

AppRegistry.registerComponent('Intervaler', () => Intervals)
```

But at a Samsung device, the interval stopped when proximity is near and turn off screen. Any ideas why does it happen?
Thanks

**Comment by IvRRimum** [comment]
The problem with `setInterval` function. React native by default doesn't support `setInterval` execution in background. 

Current workaround: https://github.com/ocetnik/react-native-background-timer

**Comment by theaidem** [comment]
Are you sure?
https://facebook.github.io/react-native/docs/timers.html

**Comment by zxcpoiu** [comment]
@theaidem 

Timer not worked properly might be not thing to do with `react-native-incall-manager`

From my experiences, timer would be suspended if app goes to background.
on android, different devices might has its own carrier customized OS, so there are some different behavior when determining "app in background". ex: some OS treat app is in background when proximity is near, but some are not.

you can run above code you attached without invoke/import any `react-native-incall-manager` stuffs, then see if timer works.

**Comment by IvRRimum** [comment]
@zxcpoiu Yeah, it was strictly `react-native` problem. My solution solved the issue for Android, ios still stops after 3 minutes. 

I haven't researched too much, but i think IOS needs some custom background job logic, to work longer than 3 minutes in background(screen off by proximity sensor).
Do you have any ideas?

**Comment by zxcpoiu** [comment]
I've never experienced call stops due to screen off by proximity. ( I have background mode enabled )
are you saying background timer stopped?

In my case, I am just try not to use background timer at all.
because nearly every OS has more and more restricted background policies that we may forced to change in the future.
