### ISSUE TITLE
Use library functions without starting the call

### ISSUE THREAD

**Issue by renanpupin** [zxcpoiu/react-native-incall-manager#37]
Would not it be feasible to be able to use library functions like setSpeakerphoneOn() and the proximity listener without starting a call?

**Comment by zxcpoiu** [comment]
yes of course!
please see discussion in #33 

TL;DR
I don't have time to refactor it into config-like API currently

**Comment by renanpupin** [comment]
Thanks for your reply.
We can update project description with that know issues. Then someone who have time can work on it.

**Comment by zxcpoiu** [comment]
it's true, will find time to write a brief blueprint on README

**Comment by zxcpoiu** [comment]
Android has been refactored. It's easier to add some config to control events than before.
I'm closing this for now. :)
