### ISSUE TITLE
Installation: issue when adding RNInCallManager and looking at Objective-C Bridging header

### ISSUE THREAD

**Issue by marcusegues** [zxcpoiu/react-native-incall-manager#39]
I'm trying to follow the instructions to get this library working in my react-native project, for ios, and am having major trouble:

```
Add files in to your project:

Open your project in xcode
find your_project directory under your project's xcodeproject root. ( it's a sub-directoory, not root xcodeproject itself )
you can do either:
directly drag your node_modules/react-native-incall-manager/ios/RNInCallManager/ into it.
right click on your_project directory, add files to your project and add node_modules/react-native-incall-manager/ios/RNInCallManager/
on the pou-up window, uncheck Copy items if needed and select Added folders: Create groups then add it. you will see a new directory named RNInCallmanager under your_project directory.
Setup Objective-C Bridging Header:

click your project's xcodeproject root, go to build setting and search Objective-C Bridging Header
set you header location, the default path is: ReactNativeProjectRoot/ios/, in this case, you should set ../node_modules/react-native-incall-manager/ios/RNInCallManager/RNInCallManager-Bridging-Header.h
```

This is what the directory structure looks like in xcode:
```
myProject
-- webRTC.framework
-- RCTWebRTC.xcodeproj
-- myProject
-- Libraries
-- voicewrtcTests
-- Products
-- Frameworks
```

**I need to add RNInCallManager to myProject/myProject, correct?**
When I do I don't get the pop-up window where I can uncheck "Copy items if needed" and select "Added folders: Create Groups".

**When I look at the build settings on myProject root directory, I do not see Objective-C Bridging Header anywhere, it's not there (I can search for it with empty results) **

How can I proceed to install this?

**Comment by Jerameel** [comment]
Also having this issue. Objective-C Bridging Header cant be found.

**Comment by Jerameel** [comment]
I solved this issue by draging the folder from finder directly. after that, the dialog will pop up. select the required options as indicated in the Readme then bridging header will finally appear.

**Comment by jay0lu** [comment]
I have the same issue with "Objective-C Bridging Header cant be found."
I add the RNInCallManager folder by `right click on your_project directory, add files to your project and add node_modules/react-native-incall-manager/ios/RNInCallManager/` and it does not work.
Drag the folder directly solve the problem.

**Comment by jay0lu** [comment]
@zxcpoiu Could you please modify the document by removing `right click on your_project directory, add files to your project and add node_modules/react-native-incall-manager/ios/RNInCallManager/`

**Comment by zxcpoiu** [comment]
@jay0lu

thanks!
do you mean:

change:

`right click on your_project directory, add files to your project and add node_modules/react-native-incall-manager/ios/RNInCallManager/`

to:
`drag node_modules/react-native-incall-manager/ios/RNInCallManager/ to your_project directory` ?

**Comment by jay0lu** [comment]
Hi @zxcpoiu 
Yes, right now the document has
<img width="887" alt="screen shot 2017-09-25 at 13 26 22" src="https://user-images.githubusercontent.com/6806195/30821957-2d6c4bcc-a1f5-11e7-8aba-140d2d1671b2.png">
The second method doesn't work in my case.  I suggese to remove the `right click on your_project directory, add files to your project and add node_modules/react-native-incall-manager/ios/RNInCallManager/`. 
Keep `drag node_modules/react-native-incall-manager/ios/RNInCallManager/ to your_project directory` only.

**Comment by zxcpoiu** [comment]
thanks @jay0lu , doc updated.
