### ISSUE TITLE
bridging header does not exist 

### ISSUE THREAD

**Issue by abhitheawesomecoder** [zxcpoiu/react-native-incall-manager#41]
I am using react native 0.38 and react-native-incall-manager 1.5.4
I am using Xcode 7.3.1 (Swift 2.2)
I have followed the steps as mentioned in the docs

but i am still getting error bridging header does not exist 
![screen shot 2017-07-25 at 10 17 45 pm](https://user-images.githubusercontent.com/3944526/28583731-d4217f30-7187-11e7-9b19-c8020f2b5326.png)
![screen shot 2017-07-25 at 10 19 30 pm](https://user-images.githubusercontent.com/3944526/28583752-df366c32-7187-11e7-8a18-868295db6952.png)

please check the screen shots

**Comment by zxcpoiu** [comment]
Ah, I know the installation process is a little bit silly.
But this mainly because you have incorrect install process.

people usually solve this via totally removed the project, and then re-create it again step by step.
you can see another issues with title something like `xxx undefined` or `xxx not build`

**Comment by abhitheawesomecoder** [comment]
I tried totally removing the project, and then re-create it again step by step. But, it's still giving the same error. I think there is some path issue with the bridging header. Have tried it with IOS 9 and XCode 7.3?

**Comment by zxcpoiu** [comment]
yes, before `2.1.0`, I use Xcode 7 and of course can run on iOS9.
until some folks helped me to upgrade to xcode8 + swift 3.

to be honest, I'm not that familiar with xcode ( I experienced a drak-age/dirty-work to made it work :( )

Some folks are more familiar with xcode / swift might help:

@sagivo 
@tsugitta
@stepanvotava

:pray:

**Comment by abhitheawesomecoder** [comment]
Ok Thanks, then I am closing the issue.

**Comment by zxcpoiu** [comment]
it's ok you leave it open till you solves it.

### my personal debug 101 is:

1. delete all project
2. delete node_modules ( rm -rf )
3. Xcode -> Product -> clean
4. close xcode
5. npm install again
6. open xcode and try the install process
