### ISSUE TITLE
Compile Errors RN 0.47.0

### ISSUE THREAD

**Issue by 8BallBomBom** [zxcpoiu/react-native-incall-manager#45]
Since upgrading i'm getting these errors on compilation.

`
\node_modules\react-native-incall-manager\android\src\main\java\com\zxcpoiu\incallmanager\InCallManagerPackage.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: \node_modules\react-native-incall-manager\android\src\main\java\com\zxcpoiu\incallmanager\InCallManagerModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: \node_modules\react-native-incall-manager\android\src\main\java\com\zxcpoiu\incallmanager\InCallManagerModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:react-native-incall-manager:compileReleaseJavaWithJavac FAILED
`

**Comment by ruddell** [comment]
This was fixed the other day in https://github.com/zxcpoiu/react-native-incall-manager/pull/43 but is unreleased

**Comment by 8BallBomBom** [comment]
Thanks for the heads up.
Will apply the fix manually for now.

**Comment by zxcpoiu** [comment]
oops, sorry for late, I've released 2.2.0

**Comment by 8BallBomBom** [comment]
Thanks :)
