### ISSUE TITLE
Failed to convert RNIncallManager.swift

### ISSUE THREAD

**Issue by jay0lu** [zxcpoiu/react-native-incall-manager#48]
When I try to implement react-native-incall-manager into my iOS project, it requires converting swift version. And the Xcode converting failed to convert RNIncallManager.swift.
![image](https://user-images.githubusercontent.com/6806195/30817245-5236fd62-a1e6-11e7-9dbd-0027018f9cab.png)
I tried to discard the change and it seems okay (It successfully builds the app).

I raise this issue because I don't know if I'm doing right.
Is there a better way to solve this problem or its bug needs to fix in the code?

Thanks.

**Comment by zxcpoiu** [comment]
Not familiar with iOS/xcode stuff though, so I can not confirm it.
If I recall it correctly, it **might** be a cache issue.
The next time it occurs, try to `Product` -> `Clean`, and see if the warning disappear

anyway, thanks for reporting!

**Comment by zxcpoiu** [comment]
As of #56, the iOS part has been changed it to objc and there is no swift anymore.
Please check latest master.

**Comment by konstantin-mohin** [comment]
@jay0lu hi, have you fixed it ?

**Comment by zxcpoiu** [comment]
@konstantin-mohin 

see #59 
https://github.com/zxcpoiu/react-native-incall-manager/issues/59#issuecomment-351849745
