### ISSUE TITLE
Low audio volume only first time after fresh install

### ISSUE THREAD

**Issue by JoostVermeulen11** [zxcpoiu/react-native-incall-manager#49]
Hello,

I have a video conferencing app. When i open a fresh install for first time, its asking for permissions etc. After that, the first time the sound always comes out of the earpiece speaker. Next times it just comes from the external speakers like it's supposed to be. Does someone knows the cause of the bug? I have tried lots of things but didn't found a solution yet. 

Joost

**Comment by zxcpoiu** [comment]
hey, I am encountering this. #40 
but don't understand the cause yet :(

**Comment by kristiansorens** [comment]
Hey Guys,

We had the same issue. refusing to switch to speaker only immediately after setting permission and working perfectly fine on subsequent attempts. looking at the NSURL logs,  We noticed that the internal `checkRecordPermission` for recording audio gets called at instantiation, and stores the value to a `self.recordPermission`

This is later checked on in the start function, and if not granted it will return.
```
guard self.recordPermission == "granted" else {
    NSLog("RNInCallManager.start(): recordPermission should be granted. state: \
    (self.recordPermission)")
    return
}
```
So all you need to do is make sure that you call the `checkRecordPermission` function before you start the in call manager. Something like:
  ```
 await InCallManager.checkRecordPermission();
 InCallManager.start({ media: "video" });
```
That got it working for us, hope it helps @zxcpoiu @JoostVermeulen11

**Comment by JoostVermeulen11** [comment]
You helped me out! thanks!!!!

**Comment by zxcpoiu** [comment]
@kristiansorens 

thanks!
this did help a lot for sure.
