### ISSUE TITLE
Add support for Xcode 9 with Swift version 3+

### ISSUE THREAD

**Issue by renanpupin** [zxcpoiu/react-native-incall-manager#53]
The library can not be converted by the new xcode 9 because it does not support swift version 2.x, just 3.x+.
Can we create a new branch with the old code and update master with the code in swift 3 or 4?

**Comment by zxcpoiu** [comment]
@renanpupin 

yes, of course.
if anyone has a PR to master contains breaking changes, I will create a branch for the old one and let the newer version PR merged into master

**Comment by zxcpoiu** [comment]
thanks for indicate! I haven't upgrade to xcode 9 yet so didn't notice it.

**Comment by zxcpoiu** [comment]
As of #56, there is no swift anymore. it has been changed it to objc. cheers.
