### ISSUE TITLE
Cannot get `setForceSpeakerphoneOn` function on iOS.

### ISSUE THREAD

**Issue by jay0lu** [zxcpoiu/react-native-incall-manager#59]
In chrome inspector, cannot find `setForceSpeakerphoneOn()` in InCallManager.
<img width="488" alt="screen shot 2017-12-10 at 19 39 08" src="https://user-images.githubusercontent.com/6806195/33811490-2cb83b5e-dde2-11e7-891f-21bf47fffbf9.png">

iOS: 11.2
"react-native": "0.47.2",
"react-native-incall-manager": "^2.2.0"

**Comment by zxcpoiu** [comment]
Can you try on the latest master?
It has been totally rewritten in objc

**Comment by jay0lu** [comment]
@zxcpoiu Hi, I Created a new project using `"react-native-incall-manager": "git://github.com/zxcpoiu/react-native-incall-manager.git"`, When I try to run react-native run-ios, I got this error on terminal
 `<unknown>:0: error: no such file or directory: '/Users/xx/project/node_modules/react-native-incall-manager/ios/RNInCallManager/RNInCallManager.swift'`
`Command /Applications/Xcode-8.3.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1`

**Comment by zxcpoiu** [comment]
@jay0lu 

The latest master use pure objc codes, there is no swift anymore.
Would you try the `clean process` described in README?
And make sure you remove `swift bridging header` in your xcode if you had used order version of this library before in your xcode

**Comment by jay0lu** [comment]
@zxcpoiu 
Thanks for reply, I found that to solve the compile problem, I need to go to `xcode -> project -> build phases -> compile sources` remove the RNIncallmanager.swift file.

**Comment by zxcpoiu** [comment]
thanks for sharing this @jay0lu
