### ISSUE TITLE
recordPermission and requestRecordPermission on iOS

### ISSUE THREAD

**Issue by oney** [zxcpoiu/react-native-incall-manager#6]
Bridging those to Javascript will be good.
```objective-c
[[AVAudioSession sharedInstance] recordPermission];
// And
[[AVAudioSession sharedInstance] requestRecordPermission:^(BOOL granted) {
}];
```
I will send a PR if I have time to do it.

**Comment by zxcpoiu** [comment]
Thanks, it makes sense!

**Comment by zxcpoiu** [comment]
@oney 

I'm doing it now.

**Comment by zxcpoiu** [comment]
@oney 

I have push a branch `fix-ios-flow` included two promise functions ( and fixed some audio routing logic)

```javascript
async checkRecordPermission() // return promise
async requestRecordPermission() // return promise
```

and one property: `recordPermission` default is 'unknow'.
after incall manager initialized, module will check current state of record permission,
so you can just write below code in `ComponentDidMount` like:

```javascript
if (InCallManager.recordPermission !== 'granted') {
    InCallManager.requestRecordPermission()
    .then((requestedRecordResult) => {
        console.log("InCallManager.requestRecordPermission() requestedRecordResult: ", requestedRecordResult);
    })
    .catch((err) => {
        console.log("InCallManager.requestRecordPermission() catch: ", err);
    });
}
```

I will implement android version soon.
let me know if someone got any problems.

**Comment by zxcpoiu** [comment]
added at Release 1.2.0
