### ISSUE TITLE
Proximity sensor doesn't work on iPhone Plus devices 

### ISSUE THREAD

**Issue by konstantin-mohin** [zxcpoiu/react-native-incall-manager#61]
I've checked it on iPhones 5,6,7,8 and it works as expected,
but when it comes to iPhones plus the sensor does not triggered.

**Comment by ianlin** [comment]
Thanks, just push a fix 11ecbe70c4ebbc95185c1985a6812ac3bbbbed4d. Not sure why I forgot to enable it when rewriting using Obj-C...

Though the proximity monitoring doesn't enable before the fix, it still works on some circumstances.

According to [this][1] it seems that `CallKit` started taking care of proximity. From my tests I use iPhone 6 with iOS version 10.3.3 the proximity works on incoming calls but fails on outgoing calls while on iOS 11 it works on both cases without this fix.

Anyway, this fix should work.

[1]: https://forums.developer.apple.com/thread/90918

**Comment by konstantin-mohin** [comment]
@ianlin thanks, 

now the sensor is working, but when it triggered I'm getting a warning message:
`Sending `Proximity` with no listeners registered.`
and if I have a function listening for the sensor event, it is not triggered, e.g.
`DeviceEventEmitter.addListener('Proximity', (device) => {// code });`

**Comment by zxcpoiu** [comment]
@konstantin-mohin 

It's a react-native warning.
The purpose of these events is, for folks can implement their own logic via event. ( not automatic )
That's the original design, as you can see in `readme`, I am planning to make it configurable but unfortunately have limited time.

Not sure if there are side effects, but if you really don't want this event, you can comment `sendEvent()` out in both java and objc at your own branch.

If you are willing to make it configurable, feel free to fire a PR then :smile:

**Comment by zxcpoiu** [comment]
Thanks for your feedback, I'm going to close this as this issue has been fixed
