### ISSUE TITLE
C++ Exception in NativeModules: java.lang.RuntimeException: Got unknown argument class: long

### ISSUE THREAD

**Issue by konstantin-mohin** [zxcpoiu/react-native-incall-manager#62]
I got the error after a successful build once I opened an app on a device.
I think the issue is related to react-native version,
my version is 0.43.4

**Comment by zxcpoiu** [comment]
Does it related to https://github.com/zxcpoiu/react-native-incall-manager/commit/29f748b8a9803979b7df85aaa5a582196be8b259 ?

You can try add back `@override` and see if it works

**Comment by konstantin-mohin** [comment]
@zxcpoiu  thanks for the quick response,

it seems no, it doesn't. 
adding` @override` back does not have any impact on the error.

it may be worth to mention that an app is crashing.

**Comment by zxcpoiu** [comment]
so it's android right?

**Comment by konstantin-mohin** [comment]
@zxcpoiu yeah, as it's clear from the title =)

so, I've looked at the issue, 
this method causes the error

`    @ReactMethod
    public void pokeScreen(long timeout) {
`

if we change timeout argument type to `int`, the error disappears.

Then I tried it on android 6.0.1 and it's working for 1-2 sec on my bluetooth device then sound goes via a phone speaker.

**Comment by zxcpoiu** [comment]
@konstantin-mohin 

Thanks, I just changed it back to `int`, seems JS doesn't have long type.

This issue has solved, for another question, would you open a new issue and provide some detailed log?
I had similar issue before before, but not sure what's the cause yet.

You can use the following command to gather related logs:

```
adb logcat -c; adb logcat -v threadtime ReactNative:V ReactNativeJS:V React:V com.oney.WebRTCModule.WebRTCModule:V InCallManager:V org.webrtc.Logging:V AudioCapabilities:V VideoCapabilities:V Camera2Enumerator:V Camera1Enumerator:V AppRTCAudioManager:V AppRTCProximitySensor:V AppRTCBluetoothManager:V InCallProximityManager:V InCallWakeLockUtils:V *:E | tee /tmp/android_logcat
```
