### ISSUE TITLE
The sound is sent to a phone speaker instead of being sent to a bluetooth device

### ISSUE THREAD

**Issue by konstantin-mohin** [zxcpoiu/react-native-incall-manager#63]
The problem is that after successful sound transmission to a bluetooth device_(for one second)_  the sound is sent to a phone speaker.

I'm using:
RN 43.4
RN webrtc: 1.58.3
Android: 6.0.1

[android_logcat.txt](https://github.com/zxcpoiu/react-native-incall-manager/files/1584811/android_logcat.txt)

**Comment by zxcpoiu** [comment]
I saw you did not give Bluetooth permission in your app.

1. please grant Bluetooth permission
2. Remove any devices other than Bluetooth one ( there is a WiredHeadset, not sure what it is )
3. I was testing Bluetooth `SCO` type, and your is `A2DP`, I'm not familiar with these, not sure if there are differences.


```
12-24 14:09:35.252 21446 21446 D InCallManager: --- updateAudioDeviceState: wired headset=true, BT state=UNINITIALIZED
12-24 14:09:35.252 21446 21446 D InCallManager: Device status: available=[], selected=null, user selected=null
12-24 14:09:35.252 21446 21446 D InCallManager: setAudioDeviceInternal(device=WIRED_HEADSET)
12-24 14:09:35.253 21446 21446 D InCallManager: New device status: available=[WIRED_HEADSET], selected=WIRED_HEADSET
12-24 14:09:35.253 21446 21446 D InCallManager: --- updateAudioDeviceState done
12-24 14:09:35.322 21446 23081 D InCallManager: startProximitySensor()
12-24 14:09:35.322 21446 23081 D InCallManager: setKeepScreenOn() true
12-24 14:09:35.322 21446 23081 D AppRTCBluetoothManager: start
12-24 14:09:35.323 21446 23081 W AppRTCBluetoothManager: Process (pid=21446) lacks BLUETOOTH permission

```

**Comment by konstantin-mohin** [comment]
@zxcpoiu thanks, 
so now it is worth mentioning in the documentation to add a bluetooth permission in an AndroidManifest file.

The first test was fine, then the functionality stopped working...

I made two logs, first one when a user connecting with already paired bluetooth device, second one when a user pair with a bluetooth device after connection.
[connect_with_paired_bluetooth.txt](https://github.com/zxcpoiu/react-native-incall-manager/files/1585804/connect_with_paired_bluetooth.txt)
[connect_with_unpaired_bluetooth.txt](https://github.com/zxcpoiu/react-native-incall-manager/files/1585808/connect_with_unpaired_bluetooth.txt)

another thing,
as I've noticed new functionality, if `setForceSpeakerphoneOn` is `true`, the proximity sensor is not triggered. Also under certain conditions if audio is sent to Bluetooth and a user set `setForceSpeakerphoneOn` to `true` and then to `false` the sound never comes back on a Bluetooth device.

**Comment by zxcpoiu** [comment]
This two logs all failed, right?
I'm really new to Bluetooth, so it may need more folks to discuss.

For what I can tell, your Bluetooth devices connected successfully and seems a A2DP devices. Webrtc tries to initial a SCO connection but failed.

After some googling, according [webrtc discuss 7476](https://bugs.chromium.org/p/webrtc/issues/detail?id=7476) and [webrtc PSA M57](https://groups.google.com/forum/#!msg/discuss-webrtc/xXjeKbW_JYI/LIXzVrKWCwAJ) webrtc does not support A2DP connection currently.

FWIW, from my limited experiences, device support SCO generally is a device for phone call, and have microphone embedded. Device uses A2DP usually is a audio player to play high quality audio stream such as a Bluetooth Speaker without a microphone.

I believe it can support A2DP in the future, like use Bluetooth as a speaker only, and use cell phone's microphone to talk. But seems it's unavailable currently.

I will add this into readme as well.

**Comment by zxcpoiu** [comment]
The behavior is like what you described. It has a `user specified audio route` design for user to select audio route, it's just not implement the interface api yet.

So now the simple use case is:

if Bluetooth is connected, route to Bluetooth
else if WiredHeadset is connected, route to Bluetooth
else if user specified an available audio route to that devices
else use default device.

As you can see, `setForceSpeakerphoneOn` logic changed to if is set to `on`, means user choose `SpeakerPhone route`, if set to `off`, means `Not specified`, so it can switch back and forth between Bluetooth device and speaker phone.

**Comment by zxcpoiu** [comment]
For proximity, it only activates when your current audio route is `EarPiece`. Other than that, proximity will NOT turn screen on/off.

**Comment by zxcpoiu** [comment]
So my suggestion would be, find a SCO Bluetooth device first and test again.

**Comment by KostyantynMohin** [comment]
@zxcpoiu 
ok,

**Comment by konstantin-mohin** [comment]
> So my suggestion would be, find a SCO Bluetooth device first and test again.

@zxcpoiu okay.
