### ISSUE TITLE
[Question] is it possible to specify a text in a microphone permission modal on IOS ?

### ISSUE THREAD

**Issue by konstantin-mohin** [zxcpoiu/react-native-incall-manager#66]
In a modal title we have this text
 "<app name>" would like to access the Microphone.
which is good, but next line bellow it is written just "Microphone permission", 
which I want to modify.

**Comment by zxcpoiu** [comment]
I don't understand this question. Does this cause any troubles?
If not, then this question should be asked on StackOverflow with tag `ios / permission / xcode`

**Comment by konstantin-mohin** [comment]
@zxcpoiu ur right, thanks
