### ISSUE TITLE
RNInCallManager.xcodeproj missing in latest builds

### ISSUE THREAD

**Issue by reimertz** [zxcpoiu/react-native-incall-manager#67]
Hi there, it seems that `RNInCallManager.xcodeproj` is missing from the packages published to npm.

**Comment by zxcpoiu** [comment]
Not sure what you mean but after `npm install` and go to `node_modules/react-native-incall-manager`
I saw `ios/RNInCallManager.xcodeproj` directory and it contains a file `project.pbxproj`

**Comment by mahtas** [comment]
As you see:
![ekran resmi 2018-01-11 15 38 01](https://user-images.githubusercontent.com/17687022/34825919-89fe9cc4-f6e5-11e7-95a8-237498968291.png)

**Comment by zxcpoiu** [comment]
Ah, I just noticed there is no need to have `RNInCallManager.xcodeproj` in version 2.x and before. ( swift version )

The current master is a totally rewritten and has an additional `RNInCallManager.xcodeproj`.
I just published current master to `3.0.0`

If you wish to use `2.x`, please see the installation process of 2.x version.

**Comment by zxcpoiu** [comment]
thanks @mahtas for  the version tip :)
