### ISSUE TITLE
Can't build on iOS - RCTBridgeModule.h not found

### ISSUE THREAD

**Issue by rcosteira79** [zxcpoiu/react-native-incall-manager#69]
Hello there. I'm trying to use this library, but I can't seem to set it up for iOS. I used react-native link and, while everything seems to be ok for Android, iOS didn't even build. I then followed all the installation steps, cleaned up, tried the steps again, and still nothing. Has anyone ever experienced this, or knows of a way to solve it?  It's a detached ExpoKit project, so my guess is it has something to do with that. Thank you in advance!

**Comment by zxcpoiu** [comment]
Looks like a integration problem. xcode didn't find `RCTBridgeModule.h` which needs to be compiled.
This plugin is for pure react-native, you can try upgrade/reinstall `react-native` properly
If you are using `expo`, check doc for `native module` on `expo`'s website.

**Comment by rcosteira79** [comment]
The only workaround I found was to add the missing headers directly on the react-native-incall-manager header search paths. The only problem here is that this has to be done whenever the node modules folder is deleted for whatever reason.

**Comment by zxcpoiu** [comment]
Closing this. If anyone has same issue, please follow https://github.com/zxcpoiu/react-native-incall-manager#clean-project-if-messed-up first, and open a new issue or PR if it still occurs.
