### ISSUE TITLE
Not firing WiredHeadset event.

### ISSUE THREAD

**Issue by Taha39** [zxcpoiu/react-native-incall-manager#7]
I have tried two methods, but none of them are firing the event: 

**Method 1:**
 import { DeviceEventEmitter } from 'react-native';

DeviceEventEmitter.addListener('WiredHeadset', function (data) {
    // --- do something with events
});
**Method 2:**
import { NativeEventEmitter, NativeModules } from 'react-native';

const nativeBridge = NativeModules.InCallManager;
const NativeModule = new NativeEventEmitter(nativeBridge);

this.wiredHeadsetListener = NativeModule.addListener('WiredHeadset', (data) => {
  // do something
});
Any help would be appreciated

**Comment by sushantdsuwal** [comment]
I did fix it by using the method below. Woking fine both on my android and ios device 

```
  eventEmitter = new NativeEventEmitter(NativeModules.InCallManager);

  eventListener = this.eventEmitter.addListener('WiredHeadset', (event) => {
    if (event.isPlugged) {
      InCallManager.setForceSpeakerphoneOn(false);
    } else {
      InCallManager.setForceSpeakerphoneOn(true);
    }
  });
```

**Comment by kait-baraa** [comment]
you need to verify that the InCallManager.start() function is already called and the call is running
