### ISSUE TITLE
Ringback issue

### ISSUE THREAD

**Issue by sm2017** [zxcpoiu/react-native-incall-manager#71]
In iOS device `ringback` is not played? but in simulator is working , what I am missing?

```js
InCallManager.start({media: 'audio', ringback: '_BUNDLE_'});
```
I also try `_DEFAULT_`and `_DTMF_`

In simulator every thing is ok but in device ringback and busy tone is not played , just ringtone is working

**Comment by sm2017** [comment]
@zxcpoiu can you help me?

**Comment by zxcpoiu** [comment]
If you are using `BUNDLE`, make sure you had put file into app follow README for iOS.
iOS doesn't have `DTMF` generator, so it will use iOS embedded sound file like `DEFAULT` 

If it can not played, it may related to the os embedded sound file doesn't exist?
You might want to try BUNDLE or try on another device.

**Comment by sm2017** [comment]
@zxcpoiu I follow README , why _BUNDLE_ works on emulator? And don't works on device?
I try on iphone 5 and 6 devices

**Comment by zxcpoiu** [comment]
Weird, if a simulator can play `_BUNDLE_` , that means, problem is not from code itself.

1. Did you see any logs like `RNInCallManager.getAudioUri(): incallmanager_ringback.mp3 not found in bundle` ?

2. Given that `ringback` / `busytone` are part of `start()` function, I guess it seems `start()` function runs well on simulator, but there is something wrong when you call `start()` on real device. You could track logs in `start()` and see if it's really started without any problem. There might have some incompatible lines which breaks `start()` function thus ringback are not played. see https://github.com/zxcpoiu/react-native-incall-manager/blob/master/ios/RNInCallManager/RNInCallManager.m#L125

**Comment by sm2017** [comment]
@zxcpoiu I run again in device to check the log , the ring back works , I don't change codes and have no idea why the code don't works on device before (work on simulator) and now works on both
