### ISSUE TITLE
IOS: cannot make sound through headset

### ISSUE THREAD

**Issue by Moussawi7** [zxcpoiu/react-native-incall-manager#79]
Hi,
I am using this plugin with [react-native-webrtc](https://github.com/oney/react-native-webrtc).
unfortunately, when the headset is initially plugged-in the sound go through the built-in speaker so i had to remove the headset then plug it again so the audio will go through the headset's speaker.
Note that no issue on Android
```
 import InCallManager from 'react-native-incall-manager';
 InCallManager.start({ media: 'audio' })
 InCallManager.setForceSpeakerphoneOn(true);
```

**Comment by zxcpoiu** [comment]
Why you do `InCallManager.setForceSpeakerphoneOn(true);`? It will force audio route to speaker anyway.
If you want to route audio through speaker phone by default, then you can use `{ media: 'video' }`.

**Comment by Moussawi7** [comment]
Thank you @zxcpoiu , you made my day
