### ISSUE TITLE
Sending "Proximity" with no listeners registered

### ISSUE THREAD

**Issue by nxz91** [zxcpoiu/react-native-incall-manager#82]
Hi,

Still get this warning, even after registering a listener with an empty callback. I don't even need to handle this event.

Am I doing something wrong?

Thanks!

**Comment by konstantin-mohin** [comment]
@nxz91 only happens on IOS ?

**Comment by nxz91** [comment]
I‘m only testing on iOS at the moment, yes

**Comment by nxz91** [comment]
Thanks!
