### ISSUE TITLE
IOS: sound disappears in background

### ISSUE THREAD

**Issue by konstantin-mohin** [zxcpoiu/react-native-incall-manager#83]
Hi, 
I'm using the latest version on my iPhone 7, 
when I switch to another application (i.e. current app goes into background state) a sound is disappearing after 1 second when i returning back the sound is appearing again.

each time Im returning I'm getting  this log
`
RNInCallManager.AudioRouteChange.Reason: RouteConfigurationChange. category=AVAudioSessionCategoryPlayAndRecord mode=AVAudioSessionModeVoiceChat
RNInCallManager.AudioRouteChange.SilenceSecondaryAudioHint: End
RNInCallManager.AudioRouteChange.SilenceSecondaryAudioHint: Unknow Value
RNInCallManager.AudioRouteChange.Reason: RouteConfigurationChange. category=AVAudioSessionCategoryPlayAndRecord mode=AVAudioSessionModeVoiceChat
RNInCallManager.AudioRouteChange.SilenceSecondaryAudioHint: End
RNInCallManager.AudioRouteChange.SilenceSecondaryAudioHint: Unknow Value
RNInCallManager.AudioRouteChange.Reason: CategoryChange. category=AVAudioSessionCategoryPlayAndRecord mode=AVAudioSessionModeVoiceChat
RNInCallManager.updateAudioRoute(): [Enter] forceSpeakerOn flag=0 media=audio category=AVAudioSessionCategoryPlayAndRecord mode=AVAudioSessionModeVoiceChat
RNInCallManager.updateAudioRoute(): did NOT overrideOutputAudioPort()
RNInCallManager.updateAudioRoute() did NOT change audio mode
RNInCallManager.AudioRouteChange.SilenceSecondaryAudioHint: End
RNInCallManager.AudioRouteChange.SilenceSecondaryAudioHint: Unknow Value
RNInCallManager.AudioRouteChange.Reason: CategoryChange. category=AVAudioSessionCategoryPlayAndRecord mode=AVAudioSessionModeVoiceChat
RNInCallManager.updateAudioRoute(): [Enter] forceSpeakerOn flag=0 media=audio category=AVAudioSessionCategoryPlayAndRecord mode=AVAudioSessionModeVoiceChat
RNInCallManager.updateAudioRoute(): did NOT overrideOutputAudioPort()
RNInCallManager.updateAudioRoute() did NOT change audio mode
RNInCallManager.AudioRouteChange.SilenceSecondaryAudioHint: Unknow Value
RNInCallManager.AudioRouteChange.Reason: CategoryChange. category=AVAudioSessionCategoryPlayAndRecord mode=AVAudioSessionModeVoiceChat
RNInCallManager.updateAudioRoute(): [Enter] forceSpeakerOn flag=0 media=audio category=AVAudioSessionCategoryPlayAndRecord mode=AVAudioSessionModeVoiceChat
RNInCallManager.updateAudioRoute(): did NOT overrideOutputAudioPort()
......
`

**Comment by konstantin-mohin** [comment]
the problem was that in the new version of Xcode does not have VoIP Capability in Background Modes, 
so you should manually modify Info.plist 

`<key>UIBackgroundModes</key>
	<array>
    <string>voip</string>
	</array>`

**Comment by zxcpoiu** [comment]
thanks for sharing this.
