### ISSUE TITLE
Stop() doesn't really terminate the call audio

### ISSUE THREAD

**Issue by niron1** [zxcpoiu/react-native-incall-manager#84]
Hi,
I have a scenario when a video call is terminated by a user.
In such case the following code is executed:
`
InCallManager.stop();
global.callSocket.emit('leave');  
`
however, the audio continues until the other party also terminates the call.
any idea?

**Comment by zxcpoiu** [comment]
Webrtc itself has their own audio logic and plays audio if stream is available.
 
InCallManager ( this lib ), does nothing to do with `terminate` call, this lib is kind of to `override` the audio settings during a call. so `InCallManager.stop();` means to stop overriding audio settings, leave webrtc handles itself.

So you need to terminate your PeerConnection / Streams in `react-native-webrtc`.
something like this:

```js
localStream.removeTrack(track);
localStream.release();
pc.close()
```
