### ISSUE TITLE
Feature request : setSpeakerphoneOn on iOS

### ISSUE THREAD

**Issue by sm2017** [zxcpoiu/react-native-incall-manager#85]
Can you please implement `setSpeakerphoneOn` on iOS?

**Comment by sm2017** [comment]
@zxcpoiu Can you help me?

**Comment by zxcpoiu** [comment]
ios seems doesn't have API to `setSpeakerPhoneOn`. just `setMode` and `setCategory`
If you want to toggle audio routing, check behaviors below and you may have the idea:

> We use `setForceSpeakerPhone` on / off / null, to toggle audio route.
if set to null, it uses default route, for audio only call, the default route is earpiece, for video, the default route is speaker phone.
>
> If a device use DEFAULT (`setForceSpeakerPhone(null)`) audio route AND Bluetooth is connected, ideally, system OS would route audio to Bluetooth. iOS works fine in this approach.
