### ISSUE TITLE
[Question] Does this library still works if i put the application on background? (Android)

### ISSUE THREAD

**Issue by fcaride** [zxcpoiu/react-native-incall-manager#88]
I want to know if the call behavior will be still working if i put the app on background on android.

Thanks!

**Comment by zxcpoiu** [comment]
I am not sure I understand your question correctly.
But the some facts FWIW

* It can still play sounds of course, but you do not have controls ( press button ) while you are in background.
* react-native not allowed JS event while app is in background
* Even your app can still work in background, you should keep your app alive and not get killed / stopped by system.
