### ISSUE TITLE
Incoming ringtone doesn't play on specific device

### ISSUE THREAD

**Issue by vink1987** [zxcpoiu/react-native-incall-manager#89]
I am using the following code when I receive an incoming call:

InCallManager.startRingtone('_BUNDLE_');

This plays ringtone on almost all the device except mine. My device is Xiaomi Redmi Note 3.

Please help.

**Comment by zxcpoiu** [comment]
Different android OS has different policy regarding `security` / `battery optimization`
You may want to check your device's security settings and permissions.
