### ISSUE TITLE
Does Not Build With Xcode 8

### ISSUE THREAD

**Issue by conover** [zxcpoiu/react-native-incall-manager#9]
95 Errors in RNIncallManager.swift

**Comment by ianlin** [comment]
Thanks for reporting this issue. We haven't tried Xcode 8 yet since it is in beta version. Just leaves this issue open and we will get back to you once we have time to test it.

**Comment by conover** [comment]
It seems like it's mostly about the conversion to Swift 3 (which Apple says will required in future version of Xcode). If you convert to Swift 2.3, everything seems good. So not super urgent.

**Comment by davidperrenoud** [comment]
Related: https://github.com/zxcpoiu/react-native-incall-manager/pull/14

**Comment by zxcpoiu** [comment]
@conover 
#14 has merged, can you confirm can it build on xcode 8?

**Comment by regentcid434** [comment]
@zxcpoiu works on xcode 8

**Comment by zxcpoiu** [comment]
thanks!

**Comment by zxcpoiu** [comment]
fixed by #14

should change to swift 3 in the future
