### ISSUE TITLE
AVAudioSessionCategoryOptionMixWithOthers not working

### ISSUE THREAD

**Issue by tombaki** [zxcpoiu/react-native-incall-manager#90]
@zxcpoiu hello sorry for my bad English,
I wan't to play music in background and mix my mic with it .
I try to change category with options and mode but without any success ,
category with option set to interruptSpokenAudioAndMixWithOthers

**Comment by zxcpoiu** [comment]
I think your use case is out of scope of this plugin, it would be better asked on StackOverflow
