### ISSUE TITLE
import com.zxcpoiu.incallmanager.InCallManagerPackage; does not exist

### ISSUE THREAD

**Issue by mhmdhsnkml** [zxcpoiu/react-native-incall-manager#93]
Here is my MainApplication.java
`package host.exp.exponent;

import com.facebook.react.ReactPackage;
import com.oney.WebRTCModule.WebRTCModulePackage;

import java.util.Arrays;
import java.util.List;

// Needed for `react-native link`
// import com.facebook.react.ReactApplication;
import com.zxcpoiu.incallmanager.InCallManagerPackage;

public class MainApplication extends ExpoApplication {

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add native modules!

        // Needed for `react-native link`
        // new MainReactPackage(),
        new InCallManagerPackage(),
        new WebRTCModulePackage()
    );
  }

  @Override
  public String gcmSenderId() {
    return getString(R.string.gcm_defaultSenderId);
  }

  @Override
  public boolean shouldUseInternetKernel() {
    return BuildVariantConstants.USE_INTERNET_KERNEL;
  }
}
`

i got this error when build the project
![image](https://user-images.githubusercontent.com/22633217/44102179-521be618-a013-11e8-9f57-1ff34020b6a7.png)

**Comment by zxcpoiu** [comment]
Please follow: https://github.com/zxcpoiu/react-native-incall-manager#clean-project-if-messed-up and try it again.

If you use Expo, please follow their native module integration guide.
