### ISSUE TITLE
fatal error: 'React/RCTBridgeModule.h' file not found #import <React/RCTBridgeModule.h> 

### ISSUE THREAD

**Issue by 7ameed** [zxcpoiu/react-native-incall-manager#95]
In file included from /../../node_modules/react-native-incall-manager/ios/RNInCallManager/RNInCallManager.m:9:
/../../node_modules/react-native-incall-manager/ios/RNInCallManager/RNInCallManager.h:12:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/hamid/Documents/Curawella/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ReactNativeIncallManager.build/Objects-normal/x86_64/RNInCallManager.o /Users/hamid/Documents/Curawella/node_modules/react-native-incall-manager/ios/RNInCallManager/RNInCallManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by zxcpoiu** [comment]
It is most likely that you don't install and config your react-native project correctly.
Please follow: https://github.com/zxcpoiu/react-native-incall-manager#clean-project-if-messed-up and try it again.

**Comment by ithustle** [comment]
hello @zxcpoiu . Is it necessary install via cocoapods and link lib on iOS project or just one of them? Because when I installed via cocoapods, I was able to build successfully but it didn't work, I mean, I can't able to start or stop a call. But after did both, the build failed but none error was presented ... Can you help me, please?

**Comment by kiko111pro** [comment]
this problem still exists. any update.??

**Comment by hitmanche** [comment]
I have the same problem. Can anyone help?
